export const baseButtonProps = Object.freeze({
	children: 'children',
	condensed: 'condensed',
	theme: 'theme',
	styleOverrides: 'styleOverrides',
	primary: 'primary',
	primaryOutline: 'primaryOutline',
	small: 'small',
	medium: 'medium',
	large: 'large',
	primaryTransparent: 'primaryTransparent',
	minorTransparent: 'minorTransparent',
	icon: 'icon',
	minor: 'minor',
});
