name: Run tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "This job was triggered by a ${{ github.event_name }} event."
      - name: Clone the ${{ github.ref }} branch of ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn test
